version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"   # 每周一次
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "priority:low"
