openapi: 3.0.0
info:
  title: wxresume API
  version: 0.1.0
paths:
  /v1/health:
    get:
      summary: Health check
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer }
                  msg: { type: string }
